name: Build Docker

on:
  push:
    branches: [ u1001350000 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      shell: bash
      run: |
        docker buildx create --use
        docker buildx build --platform=linux/amd64,linux/arm64 . -t ghcr.io/${{ github.repository_owner }}/${GITHUB_REPOSITORY##*/}:${GITHUB_REF##*/} --push
  
